//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthwindDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class NorthwindEntities : DbContext
    {
        public NorthwindEntities()
            : base("name=NorthwindEntities")
        {
            Categories = Set<Category>();
            Customers = Set<Customer>();
            Employees = Set<Employee>();
            Order_Details = Set<Order_Details>();
            Orders = Set<Order>();
            Products = Set<Product>();
            Shippers = Set<Shipper>();
            Suppliers = Set<Supplier>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Category> Categories { get; set; }
        internal virtual DbSet<Customer> Customers { get; set; }
        internal virtual DbSet<Employee> Employees { get; set; }
        internal virtual DbSet<Order_Details> Order_Details { get; set; }
        internal virtual DbSet<Order> Orders { get; set; }
        internal virtual DbSet<Product> Products { get; set; }
        internal virtual DbSet<Shipper> Shippers { get; set; }
        internal virtual DbSet<Supplier> Suppliers { get; set; }
    }
}
