'
'   Copyright (c) 2011 Microsoft Corporation.  All rights reserved.
'   Use of this sample source code is subject to the terms of the Microsoft license 
'   agreement under which you licensed this sample source code and is provided AS-IS.
'   If you did not accept the terms of the license agreement, you are not authorized 
'   to use this sample source code.  For the terms of the license, please see the 
'   license agreement between you and Microsoft.
'  
'   To see all Code Samples for Windows Phone, visit http://go.microsoft.com/fwlink/?LinkID=219604 
'  
'
Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Public Class AppResources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("sdkGlobalizationVB.AppResources", GetType(AppResources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Public Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Globalization Application.
    '''</summary>
    Public Shared ReadOnly Property AppTitle() As String
        Get
            Return ResourceManager.GetString("AppTitle", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Czech, Czech Republic.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameCsCZ() As String
        Get
            Return ResourceManager.GetString("LangRegionNameCsCZ", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Danish, Denmark.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameDaDK() As String
        Get
            Return ResourceManager.GetString("LangRegionNameDaDK", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to German, Germany.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameDeDE() As String
        Get
            Return ResourceManager.GetString("LangRegionNameDeDE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Greek, Greece.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameElGR() As String
        Get
            Return ResourceManager.GetString("LangRegionNameElGR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to English, United Kingdom.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameEnGB() As String
        Get
            Return ResourceManager.GetString("LangRegionNameEnGB", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to English, United States.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameEnUS() As String
        Get
            Return ResourceManager.GetString("LangRegionNameEnUS", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Spanish, Spain.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameEsES() As String
        Get
            Return ResourceManager.GetString("LangRegionNameEsES", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Finnish, Finland.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameFiFI() As String
        Get
            Return ResourceManager.GetString("LangRegionNameFiFI", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to French, France.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameFrFR() As String
        Get
            Return ResourceManager.GetString("LangRegionNameFrFR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Hungarian, Hungary.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameHuHU() As String
        Get
            Return ResourceManager.GetString("LangRegionNameHuHU", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Italian, Italy.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameItIT() As String
        Get
            Return ResourceManager.GetString("LangRegionNameItIT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Japanese, Japan.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameJaJP() As String
        Get
            Return ResourceManager.GetString("LangRegionNameJaJP", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Korean, Korea.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameKoKR() As String
        Get
            Return ResourceManager.GetString("LangRegionNameKoKR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Norwegian, Norway.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameNbNO() As String
        Get
            Return ResourceManager.GetString("LangRegionNameNbNO", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Dutch, Netherlands.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameNlNL() As String
        Get
            Return ResourceManager.GetString("LangRegionNameNlNL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Polish, Poland.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNamePlPL() As String
        Get
            Return ResourceManager.GetString("LangRegionNamePlPL", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Portugese, Brazil.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNamePtBR() As String
        Get
            Return ResourceManager.GetString("LangRegionNamePtBR", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Portugese, Portugal.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNamePtPT() As String
        Get
            Return ResourceManager.GetString("LangRegionNamePtPT", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Russian, Russia.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameRuRU() As String
        Get
            Return ResourceManager.GetString("LangRegionNameRuRU", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Swedish, Sweden.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameSvSE() As String
        Get
            Return ResourceManager.GetString("LangRegionNameSvSE", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chinese Simplified, PRC.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameZhCN() As String
        Get
            Return ResourceManager.GetString("LangRegionNameZhCN", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Chinese Traditional, Taiwan.
    '''</summary>
    Public Shared ReadOnly Property LangRegionNameZhTW() As String
        Get
            Return ResourceManager.GetString("LangRegionNameZhTW", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Currency Format:.
    '''</summary>
    Public Shared ReadOnly Property TextLabelCurrency() As String
        Get
            Return ResourceManager.GetString("TextLabelCurrency", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Display Language:.
    '''</summary>
    Public Shared ReadOnly Property TextLabelDispLang() As String
        Get
            Return ResourceManager.GetString("TextLabelDispLang", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Long Date format:.
    '''</summary>
    Public Shared ReadOnly Property TextLabelLngDate() As String
        Get
            Return ResourceManager.GetString("TextLabelLngDate", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Long Time Format:.
    '''</summary>
    Public Shared ReadOnly Property TextLabelLngTime() As String
        Get
            Return ResourceManager.GetString("TextLabelLngTime", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Select a Locale:.
    '''</summary>
    Public Shared ReadOnly Property TextLabelLocale() As String
        Get
            Return ResourceManager.GetString("TextLabelLocale", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Regional Format:.
    '''</summary>
    Public Shared ReadOnly Property TextLabelRegionFormat() As String
        Get
            Return ResourceManager.GetString("TextLabelRegionFormat", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Short Date Format:.
    '''</summary>
    Public Shared ReadOnly Property TextLabelShrtDate() As String
        Get
            Return ResourceManager.GetString("TextLabelShrtDate", resourceCulture)
        End Get
    End Property
End Class
