

#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------

namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class StackPanel;
                ref class TextBlock;
                ref class Image;
                ref class ComboBox;
                ref class CheckBox;
                ref class Button;
            }
        }
    }
}

namespace OCR
{
    partial ref class ExtractText : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ RootGrid;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ ControlPanel;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Output;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Content;
        private: ::Windows::UI::Xaml::Controls::Grid^ Image;
        private: ::Windows::UI::Xaml::Controls::Grid^ Result;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ ImageText;
        private: ::Windows::UI::Xaml::Controls::Image^ PreviewImage;
        private: ::Windows::UI::Xaml::Controls::Grid^ TextOverlay;
        private: ::Windows::UI::Xaml::Controls::ComboBox^ LanguageList;
        private: ::Windows::UI::Xaml::Controls::CheckBox^ OverlayResults;
        private: ::Windows::UI::Xaml::Controls::Button^ LoadButton;
        private: ::Windows::UI::Xaml::Controls::Button^ SampleButton;
        private: ::Windows::UI::Xaml::Controls::Button^ ExtractTextButton;
    };
}

